# Generated by Django 5.1.3 on 2024-11-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="age",
        ),
        migrations.AddField(
            model_name="userinfo",
            name="email",
            field=models.EmailField(default="no-email@example.com", max_length=254),
            preserve_default=False,
        ),
    ]
